### ISSUE TITLE
You mvoed the operators stuff earlier, but never covered what variables are

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/javascript-strings-lab#2]
They know what the operator is...but they don't know what variables are!

For example in ruby: https://github.com/learn-co-curriculum/variable-readme and https://github.com/learn-co-curriculum/ruby-variable-assignment

**Comment by pletcher** [comment]
This now comes after variables are introduced. :)

Although in this case, they don't have to write any variables for themselves -- the hope was that they wouldn't be bewildered just by the declaration.
