### ISSUE TITLE
Lab is passing without a space after "Hello"

### ISSUE THREAD

**Issue by galinabelyaeva** [learn-co-curriculum/javascript-strings-lab#21]
var greetSpecialGuest = "Hello," + specialGuest + "!"; 

and the tests are failing when there is a space after "Hello"

var greetSpecialGuest = "Hello, " + specialGuest + "!";

**Comment by AnnJohn** [comment]
hi @galinabelyaeva have you tried using the Ask a Question tool in Learn? Someone from our team will help you out. Thanks!
