### ISSUE TITLE
Wrong Lab Opening

### ISSUE THREAD

**Issue by ashlynnblue** [learn-co-curriculum/javascript-strings-lab#23]
In this lesson when I click "open", the previous lab opens in Learn-IDE. It is not the lab that is supposed to be completed in this lesson.

**Comment by AnnJohn** [comment]
hi @ashlynnblue could you please file a bug report for this? If you click on your profile pic in Learn, you'll see an option to Report a Bug. 

Also you can use Ask a Question to get immediate help with the problem. Thanks!
