### ISSUE TITLE
IDE learn never works

### ISSUE THREAD

**Issue by joelvosburgh** [learn-co-curriculum/javascript-strings-lab#26]
I am really glad I haven't paid money for this because I would be livid! NONE of the labs run and the f-----g IDE learn doesn't even open half the time. I'm glad this course is free, but it is a total waste of time! And I can never get any help of resolve any of this. If I go to a bootcamp, it sure as F--- is not going to be you guys!

**Comment by AnnJohn** [comment]
hi @joelvosburgh please use Ask a Question in Learn and someone from our team will be there in real time to help you troubleshoot the problem. Debugging is part of the process of coding- we don't expect you to do that on your own and that's why we have live support to help you with that process.

**Comment by joelvosburgh** [comment]
Don't bother, I don't care anymore.
--------------------------------------------
On Tue, 9/13/16, AnnJohn <notifications@github.com> wrote:

 Subject: Re: [learn-co-curriculum/javascript-strings-lab] IDE learn never works (#26)
 To: "learn-co-curriculum/javascript-strings-lab" <javascript-strings-lab@noreply.github.com>
 Cc: "joelvosburgh" <joel_vosburgh@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Tuesday, September 13, 2016, 9:30 PM
 
 hi @joelvosburgh please
 use Ask a Question in Learn and someone from our team will
 be there in real time to help you troubleshoot the problem.
 Debugging is part of the process of coding- we don't
 expect you to do that on your own and that's why we have
 live support to help you with that process. 
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
