### ISSUE TITLE
Lesson directory is missing. Can't fully complete lesson.

### ISSUE THREAD

**Issue by airyqueervin** [learn-co-curriculum/javascript-strings-lab#27]
Hi there,

I was doing the lesson for the javascript-strings-lab but I'm not able to see the directory in the IDE.  I've tried opening/reinstalling the lesson but files still don't show up. Is there a way to reset the lesson? I think it may have something to do with that or something in my cache. 

![string lab](https://cloud.githubusercontent.com/assets/22167124/18661778/5074a486-7ecc-11e6-9df6-822cdf42b234.jpg)

Thanks for the assistance. 

-A

**Comment by AnnJohn** [comment]
hi @airyqueervin could you please use Ask a Question and someone from our team will help you troubleshoot the problem right away? Thanks!
