### ISSUE TITLE
index.js and index-test.js not downloaded

### ISSUE THREAD

**Issue by jasonrvw** [learn-co-curriculum/javascript-strings-lab#31]
Opened the lesson for strings lab and the index.js and index-test.js still contains the information I entered for the previous lab. If I run learn in the console it produces the correct errors for the lab and the errors refer to these two files but I can't edit them to complete lab.

[my view](http://prntscr.com/de4qzu)

**Comment by JessRudder** [comment]
We have been unable to reproduce this issue.  Please let us know if you continue to have it.
