### ISSUE TITLE
Not Showing Run tests and submitting pull request

### ISSUE THREAD

**Issue by bfarrell4036** [learn-co-curriculum/javascript-strings-lab#32]
![screen shot 2016-12-05 at 8 50 45 pm](https://cloud.githubusercontent.com/assets/24307787/20909936/8ca81324-bb2c-11e6-9743-277dbf9b45e2.png)
I am not getting my local test run and submit pull request verified that it is completed by learn.co. 

Please advise

**Comment by karenebaker** [comment]
I am receiving the same error. Thanks!

**Comment by JessRudder** [comment]
@bfarrell4036 @karenebaker at times the queue that processes the green lights can be backed up.  Usually it will work through the back log of requests on it's own.  If you are still experiencing this issue, please let us know by clicking on "Ask a Question" and talking to a Learn Expert.
