### ISSUE TITLE
Lesson Text is doubling following test

### ISSUE THREAD

**Issue by direnc88** [learn-co-curriculum/javascript-strings-lab#35]
Every time I correct the strings and do a test it tells me that I need to repeat the corrections that I've just made. This leads me to typing in strings such as "Hello, Hello, Hello, Hello, Neil deGrasse Tyson!!" I think this lesson has an error or the IDE has a bug. If I were to type in the text that the IDE expects it will just tell me to double the text necessary to pass the test again like this: "Hello, Hello, Hello, Hello, Hello, Neil deGrasse Tyson!!!" Here is a picture of the results:
![image](https://cloud.githubusercontent.com/assets/12058472/21472916/fd2b4638-cab4-11e6-883a-ab938e64e298.png)

**Comment by ece-b** [comment]
I'm having the exact same issue.

**Comment by JessRudder** [comment]
@direnc88 @ece-b This was an IDE issue that has been resolved.  If you continue to experience this issue, please use the "Ask a Question" feature in Learn to have a Learn Expert help trouble shoot it with you.
