### ISSUE TITLE
All tests are failing

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/javascript-strings-lab#4]
When I ran this, I got 0 tests passing and 3 failing

![screen shot 2016-06-16 at 10 30 01 am](https://cloud.githubusercontent.com/assets/1892150/16120397/5631c706-33ad-11e6-8ad0-02c5f245d025.png)

Readme says that 1 should be passing and that there should be 4 tests in all. 

@jmburges

**Comment by AnnJohn** [comment]
actually nevermind. wrote that too soon. 

I guess what I was confused about was where the passing test was.

**Comment by pletcher** [comment]
I'm confused -- I read the README as saying that there are 3 tests and, if we follow along, we'll get one to pass.

Did I misread something?

**Comment by AnnJohn** [comment]
I think what got me confused was this after you tell them to run the tests the first time: 

"All but one test has failed! This is okay, and it's expected — you haven't written any code yet, after all."

So maybe was just a typo? Should it be "All three tests have failed?"

**Comment by pletcher** [comment]
Ah, yes, thanks! Fixed :)
