### ISSUE TITLE
Unable to Complete Lab

### ISSUE THREAD

**Issue by jimnshea** [learn-co-curriculum/javascript-strings-lab#40]
I am unable to complete this lab due to a error message. I am also having trouble loading the other labs in the other lessons. This is the message I see. 
<img width="1021" alt="screen shot 2017-03-18 at 12 16 10 pm" src="https://cloud.githubusercontent.com/assets/26261308/24073868/e1a7d8fc-0bd4-11e7-93ce-2af1f19c9429.png">

**Comment by JessRudder** [comment]
The message shown is an NPM warning (from the installation of the required JavaScript packages) and not an error.  It should not affect how the IDE works.  If you are still having an issue, please use the "Ask a Question" feature to get help from a Learn Expert.
