### ISSUE TITLE
Can someone else run the tests with the solution?

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/javascript-strings-lab#6]
It might be just me, but when I solved the lab and ran the tests again, they weren't passing. 

I also just copied the solution and ran tests and still got them failing. Have also been saving the files. 

But again, could be something I'm doing wrong

@jmburges

**Comment by pletcher** [comment]
Hm, the tests pass fine for me. What version of Node are you running? (`node --v`)
